import { InsertSchedule } from "@/lib/schedules/schedules.types";

export const FREQUENCY_TYPES = [
  { label: "Minute(s)", value: "minute" },
  { label: "Hour(s)", value: "hour" },
  { label: "Day(s)", value: "day" },
  { label: "Week(s)", value: "week" },
  { label: "Month(s)", value: "month" },
  { label: "Year(s)", value: "year" },
] as const;

export const DAYS = [
  { label: "Su", value: "sunday" },
  { label: "M", value: "monday" },
  { label: "Tu", value: "tuesday" },
  { label: "W", value: "wednesday" },
  { label: "Th", value: "thursday" },
  { label: "F", value: "friday" },
  { label: "Sa", value: "saturday" },
] as const;

export const STATUS_COLOR_MAP = {
  done: "success",
  no_response: undefined,
  skip: "info",
  later: "info",
} as const;

export const NO_REMINDERS_DUE_TEXT = [
  "Nothing's Due—You're Doing Great! 👍",
  "No Reminders. Just Vibes. 😎",
  "You're All Caught Up! 🎉",
  "You're Good to Go. 👍",
  "Your Brain Called—You're Free. 🧠",
  "Stillness is Progress. 🧘",
  "Rest is Part of the Routine. 🌱",
  "The Queue is Clear. 💪🏼",
  "Mission: Completed. 🚀",
  "Enjoy the downtime. 💤",
  "You're on break. 🍩",
  "Inbox: Zero. 📧",
  "Pause and appreciate. 🙏",
  "Let yourself recharge. 🔋",
  "Room to breathe. 💨",
  "Balance: Restored. 🧘‍♀️",
  "The day is yours. 🫵",
  "No loose ends. 👌",
] as const;

export const EXAMPLE_SCHEDULES: InsertSchedule[] = [
  {
    label: "Awake",
    is_sunday: true,
    is_monday: true,
    is_tuesday: true,
    is_wednesday: true,
    is_thursday: true,
    is_friday: true,
    is_saturday: true,
    is_active: true,
    start_time: "07:00",
    end_time: "21:00",
  },
  {
    label: "Evening",
    is_sunday: false,
    is_monday: true,
    is_tuesday: true,
    is_wednesday: true,
    is_thursday: true,
    is_friday: true,
    is_saturday: false,
    is_active: true,
    start_time: "18:00",
    end_time: "20:00",
  },
  {
    label: "Weekend",
    is_sunday: true,
    is_monday: false,
    is_tuesday: false,
    is_wednesday: false,
    is_thursday: false,
    is_friday: false,
    is_saturday: true,
    is_active: true,
    start_time: "10:00",
    end_time: "18:00",
  },
  {
    label: "Work",
    is_sunday: false,
    is_monday: true,
    is_tuesday: true,
    is_wednesday: true,
    is_thursday: true,
    is_friday: true,
    is_saturday: false,
    is_active: true,
    start_time: "08:00",
    end_time: "17:00",
  },
  {
    label: "Evening Routine",
    is_sunday: true,
    is_monday: true,
    is_tuesday: true,
    is_wednesday: true,
    is_thursday: true,
    is_friday: true,
    is_saturday: true,
    is_active: true,
    start_time: "18:00",
    end_time: "21:00",
  },
  {
    label: "Weekend Recharge",
    is_sunday: true,
    is_monday: false,
    is_tuesday: false,
    is_wednesday: false,
    is_thursday: false,
    is_friday: false,
    is_saturday: true,
    is_active: true,
    start_time: "10:00",
    end_time: "16:00",
  },
  {
    label: "Early Morning Focus",
    is_sunday: false,
    is_monday: true,
    is_tuesday: true,
    is_wednesday: true,
    is_thursday: true,
    is_friday: true,
    is_saturday: false,
    is_active: true,
    start_time: "05:30",
    end_time: "08:00",
  },
  {
    label: "Afternoon Deep Work",
    is_sunday: false,
    is_monday: true,
    is_tuesday: false,
    is_wednesday: true,
    is_thursday: false,
    is_friday: true,
    is_saturday: false,
    is_active: true,
    start_time: "13:00",
    end_time: "16:00",
  },
  {
    label: "Creative Block",
    is_sunday: false,
    is_monday: false,
    is_tuesday: true,
    is_wednesday: false,
    is_thursday: true,
    is_friday: false,
    is_saturday: false,
    is_active: true,
    start_time: "19:00",
    end_time: "22:00",
  },
  {
    label: "Sunday Reset",
    is_sunday: true,
    is_monday: false,
    is_tuesday: false,
    is_wednesday: false,
    is_thursday: false,
    is_friday: false,
    is_saturday: false,
    is_active: true,
    start_time: "15:00",
    end_time: "18:00",
  },
  {
    label: "Saturday Adventure",
    is_sunday: false,
    is_monday: false,
    is_tuesday: false,
    is_wednesday: false,
    is_thursday: false,
    is_friday: false,
    is_saturday: true,
    is_active: true,
    start_time: "08:00",
    end_time: "14:00",
  },
  {
    label: "Evening Exercise",
    is_sunday: false,
    is_monday: true,
    is_tuesday: false,
    is_wednesday: true,
    is_thursday: false,
    is_friday: true,
    is_saturday: false,
    is_active: true,
    start_time: "17:00",
    end_time: "19:00",
  },
  {
    label: "Wind Down",
    is_sunday: true,
    is_monday: true,
    is_tuesday: true,
    is_wednesday: true,
    is_thursday: true,
    is_friday: true,
    is_saturday: true,
    is_active: true,
    start_time: "21:00",
    end_time: "23:30",
  },
] as const;